### ISSUE TITLE
Error running getDiversityStats

### ISSUE THREAD

**Issue by llq0325** [CMWbio/geaR#1]
Hi Christopher,

I got the following error when I try to run the example data:
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘getDiversityStats’ for signature ‘"SeqVarGDSClass", "standardGeneric"’
My R version is 3.5.3.

regards,

L

**Comment by CMWbio** [comment]
Hi L,

Sorry for the delay. This package is currently under development and although it is usable, usage may contain some risks at this point.
But to answer your issue, the example data is currently not on the github.

I will add a disclaimer to the readme. 

Cheers

Chris
