### ISSUE TITLE
Installation requires additional packages

### ISSUE THREAD

**Issue by jimmybgammyknee** [CMWbio/geaR#2]
Installing from devtools requires packages "ape" and "combinat"

Got additional warnings as well
```replacing previous import ‘future::values’ by ‘rtracklayer::values’ when loading ‘geaR’```

**Comment by CMWbio** [comment]
Should be fixed now, could you try a reinstall?

**Comment by jimmybgammyknee** [comment]
Looks ok at the moment, although its difficult for me to delete and reinstall those dependencies
